on: 
  pull_request:
    branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.8'
          show-versioninfo: true
      - name: Install JuliaFormatter and check formatting
        run: |
          julia -e '
          using Pkg; 
          Pkg.add("JuliaFormatter");
          using JuliaFormatter;
          if !format(".", verbose=true)
          @error "Some files have not been formatted !!!";
          exit(1);
          end'
      - uses: julia-actions/julia-buildpkg@v1
      - name: "Run Tests"
        uses: julia-actions/julia-runtest@v1
        with:
          annotate: true
